name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed
    branches:
      - dev
      - main
      - QA

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: SSH into EC2
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_KEY }}
        script: |
          if ! command -v docker &> /dev/null; then
            sudo apt update
            sudo apt install -y docker.io
            sudo systemctl start docker
            sudo systemctl enable docker
            sudo usermod -aG docker $USER
            sudo systemctl restart docker
          else
            echo "Docker install"
          fi
          
          if ! sudo systemctl is-active --quiet docker; then
            sudo systemctl start docker
          fi

    - name: Pull Docker image
      run: sudo docker pull ${{ secrets.DOCKER_USERNAME }}/authservice:qa
    
    - name: Stop docker container
      run: sudo docker stop $(docker ps -q) || true
    
    - name: Delete old docker container
      run: sudo docker rm -f authservice-container || true
    
    - name: Run Docker Container
      run: sudo docker run -d -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/authservice:qa