name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: SSH into EC2
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_KEY }}
        script: |
          # Verifica si Docker está instalado
          if ! command -v docker &> /dev/null; then
            sudo apt update
            sudo apt install -y docker.io
            sudo systemctl start docker
            sudo systemctl enable docker
            sudo usermod -aG docker $USER
            sudo systemctl restart docker
          else
            echo "Docker is already installed."
          fi

          if ! sudo systemctl is-active --quiet docker; then
            sudo systemctl start docker
          fi

    - name: Pull Docker image
      run: |
        if [[ "${{ github.event.workflow_run.head_branch }}" == "QA" ]]; then
          TAG="qa"
        elif [[ "${{ github.event.workflow_run.head_branch }}" == "main" ]]; then
          TAG="prod"
        else
          exit 1
        fi

        sudo docker pull ${{ secrets.DOCKER_USERNAME }}/authservice:$TAG

    - name: Stop and remove old container
      run: |
        sudo docker stop authservice-container || true
        sudo docker rm -f authservice-container || true

    - name: Run Docker Container
      run: |
        if [[ "${{ github.event.workflow_run.head_branch }}" == "QA" ]]; then
          TAG="qa"
        elif [[ "${{ github.event.workflow_run.head_branch }}" == "main" ]]; then
          TAG="prod"
        else
          exit 1
        fi

        sudo docker run -d -p 3000:3000 --name authservice-container ${{ secrets.DOCKER_USERNAME }}/authservice:$TAG